version: '3.9'

services:
  test:
    build: .
    command: pytest -v tests/integration
    depends_on:
      test-db:
        condition: service_healthy
    environment:
      - SQLALCHEMY_DATABASE_URI=${TEST_DATABASE_URL}
      - DATABASE_URL=${TEST_DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - PYTHONPATH=.
    volumes:
      - .:/app
    working_dir: /app

  test-db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${TEST_DB_NAME}
    ports:
      - "5435:5432"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${TEST_DB_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5