"""Initial migration

Revision ID: 12f928fd6064
Revises: 
Create Date: 2025-03-28 17:27:05.512110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12f928fd6064'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general_classifiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scheme', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme', 'description', name='uq_scheme_description')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('_password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tenders',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ocid', sa.String(length=22), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_modified', sa.DateTime(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('value_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('enquiry_period_start_date', sa.DateTime(), nullable=True),
    sa.Column('enquiry_period_end_date', sa.DateTime(), nullable=True),
    sa.Column('tender_period_start_date', sa.DateTime(), nullable=True),
    sa.Column('tender_period_end_date', sa.DateTime(), nullable=True),
    sa.Column('auction_period_start_date', sa.DateTime(), nullable=True),
    sa.Column('auction_period_end_date', sa.DateTime(), nullable=True),
    sa.Column('award_period_start_date', sa.DateTime(), nullable=True),
    sa.Column('award_period_end_date', sa.DateTime(), nullable=True),
    sa.Column('notice_publication_date', sa.DateTime(), nullable=True),
    sa.Column('general_classifier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['general_classifier_id'], ['general_classifiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bids',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tender_id', sa.String(length=32), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('value_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tenderer_id', sa.String(), nullable=True),
    sa.Column('tenderer_legal_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complaints',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tender_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('date_submitted', sa.DateTime(), nullable=True),
    sa.Column('date_answered', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('highlighted_keywords', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tender_id', sa.String(length=50), nullable=False),
    sa.Column('change_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_documents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tender_id', sa.String(length=32), nullable=False),
    sa.Column('document_of', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('hash', sa.Text(), nullable=True),
    sa.Column('date_published', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tender_id', name='UK_UserSubscriptions_user_id_tender_id')
    )
    op.create_table('violation_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.String(length=50), nullable=False),
    sa.Column('discriminatory_requirements_score', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('unjustified_high_price_score', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('tender_documentation_issues_score', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('procedural_violations_score', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('technical_specification_issues_score', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('date_calculated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('awards',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tender_id', sa.String(length=32), nullable=False),
    sa.Column('bid_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('value_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('award_date', sa.DateTime(), nullable=True),
    sa.Column('complaint_period_start_date', sa.DateTime(), nullable=True),
    sa.Column('complaint_period_end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bid_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bid_id', sa.String(length=32), nullable=False),
    sa.Column('change_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complaint_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('complaint_id', sa.String(length=32), nullable=False),
    sa.Column('change_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_document_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('change_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['tender_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('award_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('award_id', sa.String(length=32), nullable=False),
    sa.Column('change_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['award_id'], ['awards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('award_changes')
    op.drop_table('tender_document_changes')
    op.drop_table('complaint_changes')
    op.drop_table('bid_changes')
    op.drop_table('awards')
    op.drop_table('violation_scores')
    op.drop_table('user_subscriptions')
    op.drop_table('tender_documents')
    op.drop_table('tender_changes')
    op.drop_table('complaints')
    op.drop_table('bids')
    op.drop_table('tenders')
    op.drop_table('users')
    op.drop_table('general_classifiers')
    # ### end Alembic commands ###
