"""violation score json

Revision ID: 9d0ae02f8979
Revises: aae8753290fb
Create Date: 2025-05-05 15:49:42.474859

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d0ae02f8979'
down_revision = 'aae8753290fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('violation_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scores', sa.JSON(), nullable=True))
        batch_op.drop_column('discriminatory_requirements_score')
        batch_op.drop_column('technical_specification_issues_score')
        batch_op.drop_column('unjustified_high_price_score')
        batch_op.drop_column('procedural_violations_score')
        batch_op.drop_column('date_calculated')
        batch_op.drop_column('tender_documentation_issues_score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('violation_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tender_documentation_issues_score', sa.NUMERIC(precision=5, scale=3), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date_calculated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('procedural_violations_score', sa.NUMERIC(precision=5, scale=3), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('unjustified_high_price_score', sa.NUMERIC(precision=5, scale=3), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('technical_specification_issues_score', sa.NUMERIC(precision=5, scale=3), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('discriminatory_requirements_score', sa.NUMERIC(precision=5, scale=3), autoincrement=False, nullable=True))
        batch_op.drop_column('scores')

    # ### end Alembic commands ###
